Demoscopesis/urls.py
from Demoscopesis import views
from django.urls import re_path
from django.contrib import admin

app_name = 'Demoscopesis'
urlpatterns = [
	#/Demoscopesis/
	re_path(r'^$', views.index, name='index'),
	#/Demoscopesis/5/
	re_path(r'^(?P<polls_id>[0-9]+)/$', views.moreInfo, name='moreInfo'),
	#/Demoscopesis/5/vote
	re_path(r'^(?P<polls_id>[0-9]+)/vote/$', views.vote, name='vote'),
	#/Demoscopesis/create
	re_path(r'^create/$', views.create_poll, name='createPoll'),
	#/Demoscopesis/edit/5/
	#re_path(r'^/edit/(?P<polls_id>[0-9]+)/$', views.edit, name='edit'),
]

admin.site.site_header = 'Epitome administration'
admin.site.site_title = 'Epitome administration'
admin.site.index_title = 'Home'

Epitome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Agora import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from django.urls import path

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^home/', views.homePage, name='home'),
    #url(r'^user/', include('Propylaea.urls', namespace="Propylaea")),
    #url(r'^demoscopesis/', include('demoscopesis.urls', namespace="demoscopesis")),
    #url(r'^.*/$', RedirectView.as_view(url='/home/')),
    #url(r'^$', RedirectView.as_view(url='/home/'))
	
	path('admin/', admin.site.urls),
	path('about/', views.aboutPage, name='about'),
	#path('user/', include('Propylaea.urls', namespace='Propylaea')),
	path('user/', include('allauth.urls')),
	path('demoscopesis/', include('Demoscopesis.urls', namespace='Demoscopesis')),
	path('episkopesis/', include('Episkopesis.urls')),
	url(r'^.*/$', RedirectView.as_view(url='/episkopesis/')),
	url(r'^$', RedirectView.as_view(url='/episkopesis/'))
]

urlpatterns += staticfiles_urlpatterns()

Demoscopesis/models.py
#from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, Group


class PollCat(models.Model):
	PCAT_CAT = models.CharField("Poll category", max_length=100)                                         # the category of the poll
	def __str__(self):
		return self.PCAT_CAT
	class Meta:
		verbose_name = 'Poll category'
		verbose_name_plural = 'Poll categories'


class Poll(models.Model):
	PL_TITLE = models.CharField("Title", max_length=200)                                                 # the title of the poll
	PL_SHRBODY = models.CharField("Short body", max_length=500)                                          # the short body of the poll
	PL_BODY = models.CharField("Body", max_length=15000)                                                 # the body (main text) of the poll
	PL_CREATION = models.DateTimeField("Creation date", default = timezone.now)                          # the creation date and time of the poll
	PL_STARTDT = models.DateTimeField("Starting date")                                                   # the starting date and time of the poll
	PL_ENDDT = models.DateTimeField("Ending date")                                                       # the ending date and time of the poll
	USER = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="User")                        # the user who created the poll
	POLLCAT = models.ManyToManyField(PollCat, verbose_name="Poll category")                              # the category of the poll
	def __str__(self): 
		return "%s %s" % (self.PL_TITLE, self.PL_SHRBODY)


class PollChoice(models.Model):
	POLL = models.ForeignKey(Poll, related_name='PChoice', on_delete=models.CASCADE)                     # key to Polls table
	PC_CHOICE = models.CharField("Choice", max_length=30)                                                # the vote choice
	PC_VOTES = models.IntegerField("Votes", default=0)                                                   # the number of votes
	def __str__(self):
		return self.PC_CHOICE


class Voter(models.Model):
	USER = models.ForeignKey(User, on_delete=models.CASCADE)
	POLL = models.ForeignKey(Poll, on_delete=models.CASCADE)


class Issue(models.Model):
	IS_CODE = models.CharField("Code", max_length=200)                                                   # the code of the issue
	IS_TITLE = models.CharField("Title", max_length=200)                                                 # the title of the issue
	IS_SHRBODY = models.CharField("Short body", max_length=300)                                          # the short body of the issue
	IS_BODY = models.CharField("body", max_length=1000)                                                  # the body (main text) of the issue
	IS_CREATION = models.DateTimeField("Creation date", default = timezone.now)                          # the creation date and time of the issue
	IS_CODE2 = models.CharField("Code 2", max_length=200, blank = True)                                  # the code2 of the issue (protocol number, approval number)
	USER = models.ForeignKey(User, on_delete=models.CASCADE)                                             # the user (admin) who created the issue
	UGROUP = models.ForeignKey(Group, on_delete=models.CASCADE)                                          # the group of the user that created the issue
	def __str__(self): 
		return "%s %s" % (self.IS_TITLE, self.IS_SHRBODY)


class Evidence(models.Model):
	EV_FLD1 = models.CharField(max_length=1000)                                                          # What has happened?
	EV_FLD2 = models.CharField(max_length=1000)                                                          # Why is it important?
	EV_FLD3 = models.CharField(max_length=1000)                                                          # Who has been affected?
	EV_FLD4 = models.CharField(max_length=1000)                                                          # How and why did it happen?
	EV_FLD5 = models.CharField(max_length=1000)                                                          # Where did it occur?
	EV_FLD6 = models.CharField(max_length=1000)                                                          # When did it occur?
	EV_FLD7 = models.CharField(max_length=1000)                                                          # How much is the cost?
	EV_FLD8 = models.CharField(max_length=1000)                                                          # How long did it last?
	ISSUE = models.ForeignKey(Issue, on_delete=models.CASCADE)                                           # key to Issues table

Demoscopesis/forms.py
from django import forms
from django.forms import ModelForm, Textarea, modelform_factory, modelformset_factory
from Demoscopesis.models import Poll, PollChoice
#from django.utils import timezone

class PollForm(ModelForm):
	class Meta:
		model = Poll
		fields = ('PL_TITLE', 'PL_SHRBODY', 'PL_BODY', 'POLLCAT')
		widgets = {
			'PL_TITLE' : forms.TextInput(attrs={'type':'text','id':'title','class':'form-control','required': True, 'autofocus': True, 'maxlength':200}),
			'PL_SHRBODY' : Textarea(attrs={'id':'shortbody','class':'form-control','rows':'3', 'required': True, 'maxlength':500}),
			'PL_BODY' : Textarea(attrs={'id':'body','class':'form-control','rows':'10', 'required': True, 'maxlength':15000}),
			#'PL_STARTDT' : forms.TextInput(attrs={'type':'date','id':'startdate','class':'form-control','required': True}),
			#'PL_ENDDT' : forms.TextInput(attrs={'type':'date','id':'enddate','class':'form-control','required': True}),
			#'PL_STIME' : forms.TextInput(attrs={'type':'text','id':'stime','class':'form-control','required': True}),
			#'POLLCAT' : forms.TextInput(attrs={'type':'text','id':'form-categories','class':'form-control', 'style':'display:none' ,'required': True})
			'POLLCAT' : forms.CheckboxSelectMultiple()
		}
	
	#def __init__(self, *args, **kwargs):
		#self.request = kwargs.pop("request")
		#super(PollForm, self).__init__(*args, **kwargs)
		#self.fields['USER'].initial = self.request.user.id
		#self.fields['PL_CREATION'].initial = timezone.now

class PollChoiceForm(ModelForm):
	class Meta:
		model = PollChoice
		fields = ('PC_CHOICE',) # Fields is not a String, comma is needed.
		widgets = {
			'PC_CHOICE' : forms.TextInput(attrs={'type':'hidden', 'id':'payload' ,'class':'form-control','required': True, 'maxlength':30})
		}
		
#PollChoiceFormSet = modelformset_factory(PollChoice, form=PollChoiceForm, extra=2)



PollChoiceFormSet = modelformset_factory(
    PollChoice,
    fields=('PC_CHOICE', ),
    extra=2,
    widgets={'PC_CHOICE': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter choice here'
        })
    }
)

Demoscopesis/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages
from Demoscopesis.forms import PollForm, PollChoiceFormSet
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import F, Sum

from .models import Poll, PollChoice, Voter


@login_required(login_url='/user/login/')
def index(request):
    poll_list = Poll.objects.order_by('-PL_CREATION')
    template = loader.get_template('Demoscopesis/index.html')
    paginator = Paginator(poll_list, 20)

    page = request.GET.get('page')
    latest_poll_list = paginator.get_page(page)

    context = {
        'latest_poll_list': latest_poll_list,
    }
    return HttpResponse(template.render(context, request))


@login_required(login_url='/user/login/')
def create_poll(request):
    if request.method == 'POST':
        PollsForm = PollForm(request.POST)
        formset = PollChoiceFormSet(request.POST)
        if all([PollsForm.is_valid(), formset.is_valid()]):
            poll = PollsForm.save(commit=False)
            poll.USER = request.user
            poll.PL_CREATION = timezone.now()
            poll.PL_STARTDT = timezone.now()
            poll.PL_ENDDT = timezone.now() + timezone.timedelta(days=7)
            poll.save()
            for form in formset:
                poll_choice = form.save(commit=False)
                poll_choice.POLL = poll
                poll_choice.save()
            return redirect('Demoscopesis:index')
    else:
        PollsForm = PollForm()
        formset = PollChoiceFormSet(queryset=PollChoice.objects.none())
    return render(request, 'Demoscopesis/poll-edit.html', {
        'PollForm': PollsForm,
        'PollChoiceFormSet': formset,
    })


@login_required(login_url='/user/login/')
def moreInfo(request, polls_id):
    poll = get_object_or_404(Poll, pk=polls_id)
    template = loader.get_template('Demoscopesis/poll.html')
    nowDt = timezone.localtime(timezone.now())
    if poll.PL_ENDDT < nowDt:
        poll = get_object_or_404(Poll.objects.all().annotate(total_votes=Sum('PChoice__PC_VOTES')), pk=polls_id)
    context = {
        'poll': poll,
        'nowdt': nowDt,
    }
    return HttpResponse(template.render(context, request))


@login_required(login_url='/user/login/')
def vote(request, polls_id):
    poll = get_object_or_404(Poll, pk=polls_id)
    if Voter.objects.filter(POLL_id=polls_id, USER_id=request.user.id).exists():
        messages.add_message(request, messages.ERROR, 'You have already voted.')
        return HttpResponseRedirect(reverse('Demoscopesis:index'))
    else:
        try:
            selected_choice = poll.PChoice.get(pk=request.POST['choice'])
        except (KeyError, PollChoice.DoesNotExist):  # probably wrong
            # Redisplay the question voting form.
            nowDt = timezone.localtime(timezone.now())
            return render(request, 'Demoscopesis/poll.html', {
                'poll': poll,
                'nowdt': nowDt,
                'error_message': "Please select a choice.",
            })
        else:
            selected_choice.PC_VOTES = F('PC_VOTES') + 1
            selected_choice.save()
            v = Voter(USER=request.user, POLL=poll)
            v.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            messages.add_message(request, messages.SUCCESS, 'Vote submited successfully.')
            return HttpResponseRedirect(reverse('Demoscopesis:index'))  # , args=(poll.id,)))

Demoscopesis/templates/Demoscopesis/poll-edit.html
{% extends '_base.html' %} 
{% load static %} 

{% block body %}
        <div id="wrapper">

    {% include '_sidebar.html' %}

    {% include '_navbar.html' %}

            <div class="mt-5" id="page-content-wrapper">
                <div class="container">

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Too few options!</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                            You need at least 2 options for people to vote on.
                            </div>
                            <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                        </div>
                    </div>

                    <div class="my-3">
                        <h2 class="text-center"><b>Poll Creation</b></h2>
                    </div>

                    <form id="form-body" action="{% url 'Demoscopesis:createPoll' %}" method="post" class="poll-form" role="form" data-parsley-validate novalidate>
						{% csrf_token %}
                        <div class="container-fluid shadow py-5">
                            <div class="row">            
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Title</b></label>
                                        <div id="title" class="controls">
                                            {{ PollForm.PL_TITLE }}
                                            <p id="title-counter" class="text-right"></p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Short Body</b></label>
                                        <div id="shBody" class="controls">
                                            {{ PollForm.PL_SHRBODY }}
                                            <p id="short-body-counter" class="text-right"></p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Body</b></label>
                                        <div id="body" class="controls">
                                            {{ PollForm.PL_BODY }}
                                            <p id="body-counter" class="text-right"></p>
                                        </div>
                                    </div>
                                    <!--<div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Start Date</b></label>
                                        <div class="form-row">
                                            <div class=" col-md-8 controls" id="startDt" >
                                                {{ PollForm.PL_STARTDT }} 
                                            </div>
                                            <div class="col-md-4">
                                                <div class="input-group">
                                                    {{ PollForm.PL_STIME }}
                                                    <input type="text" id="sinput" class="form-control">
                                                    <div class="input-group-append">
                                                        <button class="btn btn-outline-secondary" type="button" id="shour">Select</button>    
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>End Date</b></label>
                                        <div class="form-row">
                                            <div class=" col-md-8 controls" id="startDt" >
                                                {{ PollForm.PL_ENDDT }} 
                                            </div>
                                            <div class="col-md-4">
                                                <div class="input-group">
                                                    {{ PollForm.PL_STIME }}
                                                    <input type="text" id="einput" class="form-control">
                                                    <div class="input-group-append">
                                                        <button class="btn btn-outline-secondary" type="button" id="ehour">Select</button>    
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>-->
                                    <!--<div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Code</b></label>
                                        <div id="code" class="controls">
                                            {{ PollForm.PL_CODE }} 
                                        </div>
                                    </div>-->
									   <div class="form-group">
									       <label class="control-label control-label-left col-sm-3" for="field2"><b>Category</b></label>
                                            {{ PollForm.POLLCAT }}
                                        </div>
                                    <!--<label class="control-label control-label-left col-sm-3" for="field2"><b>Category</b></label>
                                    <div class="">  
                                        <div class="poll-form px-3 pb-3" id="categories" ></div>
                                    </div>-->
                                    <hr />
                                    <div class="form-group">
                                        <!--<div class="row">
                                            <div class="col-6">
                                                <label class="control-label control-label-left float-left mx-3"><b>Voting Choices</b></label>
                                            </div>
                                            <div class="col-6"|>
                                                <button id="add" type="button" class="btn btn-outline-info float-right" onclick="addOption()"><b>+</b></button>
                                            </div>
                                        </div>-->
                                        {{ PollChoiceFormSet.management_form }}
											{% for form in PollChoiceFormSet %}
											<div class="row form-row spacer">
												<div class="col-4">
													<div class="input-group">
														{{ form.PC_CHOICE }}
														<div class="input-group-append">
															<button class="btn btn-success add-form-row">+</button>
														</div>
													</div>
												</div>
											</div>
											{% endfor %}
											
											
											
											
											
											
                                        <!--<div id="choice" class="controls mt-3">
                                            {{ PollChoiceFormSet }}
                                        </div>-->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group text-center mt-3">
                            <div class="form-group text-center">
                            <!--<button id="submit" type="submit" class="btn btn-success">Submit</button>-->
							      <button id="submit" type="submit" class="btn btn-success">Submit</button>
                                <button id="cancel" type="button" class="btn btn-danger" onclick="window.history.back()">Cancel</button>
                            
                            </div>
                        </div>
					  </form>
                </div>
            </div>
        </div>
        {% endblock %} 


{% block scripts %}
<script src="{% static "js/jquery-3.3.1.min.js"%}"></script>
<script src="{% static "js/jquery.formset.min.js"%}"></script>
<script src="{% static "js/bootstrap.bundle.min.js"%}"></script>
<script src="{% static "js/sidebar.js"%}"></script>
<script src="{% static "js/clockpicker.js"%}"></script>
<script src="{% static "js/taggle.js"%}"></script>
<script src="{% static "js/poll-edit.js"%}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var title_max = 200;
        var short_body_max = 500;
        var body_max = 15000;

        $('#title-counter').html(title_max + ' characters remaining');
        $('#short-body-counter').html(short_body_max + ' characters remaining');
        $('#body-counter').html(body_max + ' characters remaining');

        $('#title').keyup(function() {
            var title_text_length = $('input#title').val().length;
            var title_text_remaining = title_max - title_text_length;
            $('#title-counter').html(title_text_remaining + ' characters remaining');
        });

        $('#shortbody').keyup(function() {
            var short_text_length = $('textarea#shortbody').val().length;
            var short_text_remaining = short_body_max - short_text_length;
            $('#short-body-counter').html(short_text_remaining + ' characters remaining');
        });

        $('#body').keyup(function() {
            var text_length = $('textarea#body').val().length;
            var text_remaining = body_max - text_length;
            $('#body-counter').html(text_remaining + ' characters remaining');
        });
    });

    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }

    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input').each(function() {
            var name = $(this).attr('name')
            if(name) {
                name = name.replace('-' + (total-1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        var conditionRow = $('.form-row:not(:last)');
        conditionRow.find('.btn.add-form-row')
        .removeClass('btn-success').addClass('btn-danger')
        .removeClass('add-form-row').addClass('remove-form-row')
        .html('-');
        return false;
    }

    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1){
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i=0, formCount=forms.length; i<formCount; i++) {
                $(forms.get(i)).find(':input').each(function() {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }

    $(document).on('click', '.add-form-row', function(e){
        e.preventDefault();
        cloneMore('.form-row:last', 'form');
        return false;
    });

    $(document).on('click', '.remove-form-row', function(e){
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });

</script>
{% endblock %}

Demoscopesis/templates/Demoscopesis/poll.html
{% extends '_base.html' %} 
{% load static %} 

{% block body %}
<div id="wrapper">

    {% include '_sidebar.html' %}

    {% include '_navbar.html' %}  
    
    {% if poll.PL_ENDDT > nowdt %}
    <form action="{% url 'Demoscopesis:vote' poll.id %}" method="post">
        <div id="page-content-wrapper">
            <div class="container mt-5">
                <div class="card mt-3">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-12 col-md-6 text-center text-sm-center text-md-left"><h5>Created by: {{ poll.USER }}</h5></div>
                            <div class="col-sm-12 col-md-6 text-center text-sm-center text-md-right"><h5>Created on: {{ poll.PL_STARTDT }}</h5></div>
                        </div>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title">{{ poll.PL_TITLE }}</h1>
                        <p class="card-text">{{ poll.PL_BODY }}</p>
                    </div>
                    <div class="card-footer text-center">
                        {% csrf_token %} {% for choice in poll.PChoice.all %}
                        <button type="submit" name="choice" class="btn btn-outline-primary" value="{{ choice.id }}">{{ choice.PC_CHOICE }}</button>
                        {% endfor %}
                        <a class="btn btn-danger" href="/demoscopesis" role="button">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </form>

    {% else %}

    <div id="page-content-wrapper">
        <div class="container mt-5">
            <div class="card">
                <div class="card-header text-center">
                    <h4>Results</h4>
                </div>
                <div class="card-body" id="results-card" data-progress-max="{{ poll.total_votes }}">
                    {% for choice in poll.PChoice.all %}
                    <h4>{{ choice.PC_CHOICE }}</h4>
                    <div class="progress" data-progress-value="{{ choice.PC_VOTES }}">
                        <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="" aria-valuemin="0" aria-valuemax=""></div>
                    </div>
                    {% endfor %}
                </div>
                <div class="card-footer text-center">
                    <h4>Total number of voters:
                        <span class="text-danger">{{ poll.total_votes }}</span>
                    </h4>
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-header">
                    <div class="row">
                        <div class="col-sm-12 col-md-6 text-center text-sm-center text-md-left"><h5>Created by: {{ poll.USER }}</h5></div>
                        <div class="col-sm-12 col-md-6 text-center text-sm-center text-md-right"><h5>Created on: {{ poll.PL_STARTDT }}</h5></div>
                    </div>
                </div>
                <div class="card-body">
                    <h1 class="card-title">{{ poll.PL_TITLE }}</h1>
                    <p class="card-text">{{ poll.PL_BODY }}</p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %} 

{% block scripts %}
<script src="{% static "js/jquery-3.3.1.min.js"%}"></script>
<script src="{% static "js/jquery.formset.min.js"%}"></script>
<script src="{% static "js/bootstrap.bundle.min.js"%}"></script>
<script src="{% static "js/sidebar.js"%}"></script>
<script>
    window.onload = voteResults();

     function voteResults(){
     if (document.getElementById("results-card") != null && document.getElementsByClassName("progress") != null ){
        var total = document.getElementById("results-card").dataset.progressMax;
        var votecount = document.getElementsByClassName("progress");
            for (var i = 0; i < votecount.length; i++) {
                res = ( votecount[i].dataset.progressValue / total ) * 100;
                votecount[i].firstElementChild.style.width= res + '%';
                votecount[i].firstElementChild.innerHTML = '<b>' + votecount[i].dataset.progressValue + '</b>';
            }
         }
    }
</script>
{% endblock %}